version: '3.8'

services:
  api:
    build: ./api
    restart: unless-stopped
    ports:
      - "4444:4444"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - api
    volumes:
      - ./frontend:/app
